In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
from sklearn import preprocessing

In [20]:
df=pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv')

In [21]:
df

,Unnamed: 0,Unnamed: 0.1,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,0,0,PAIDOFF,1000,30,9/8/2016,10/7/2016,45,High School or Below,male
1,2,2,PAIDOFF,1000,30,9/8/2016,10/7/2016,33,Bechalor,female
2,3,3,PAIDOFF,1000,15,9/8/2016,9/22/2016,27,college,male
3,4,4,PAIDOFF,1000,30,9/9/2016,10/8/2016,28,college,female
4,6,6,PAIDOFF,1000,30,9/9/2016,10/8/2016,29,college,male
...,...,...,...,...,...,...,...,...,...,...
341,394,394,COLLECTION,800,15,9/11/2016,9/25/2016,32,High School or Below,male
342,395,395,COLLECTION,1000,30,9/11/2016,10/10/2016,25,High School or Below,male
343,397,397,COLLECTION,800,15,9/12/2016,9/26/2016,39,college,male
344,398,398,COLLECTION,1000,30,9/12/2016,11/10/2016,28,college,male
345,399,399,COLLECTION,1000,30,9/12/2016,10/11/2016,26,college,male

In [22]:
data=df.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)
data['customer']=range(0,len(df))


data=data[['customer','age','Gender','terms','Principal','effective_date','due_date','education','loan_status']]
data

,customer,age,Gender,terms,Principal,effective_date,due_date,education,loan_status
0,0,45,male,30,1000,9/8/2016,10/7/2016,High School or Below,PAIDOFF
1,1,33,female,30,1000,9/8/2016,10/7/2016,Bechalor,PAIDOFF
2,2,27,male,15,1000,9/8/2016,9/22/2016,college,PAIDOFF
3,3,28,female,30,1000,9/9/2016,10/8/2016,college,PAIDOFF
4,4,29,male,30,1000,9/9/2016,10/8/2016,college,PAIDOFF
...,...,...,...,...,...,...,...,...,...
341,341,32,male,15,800,9/11/2016,9/25/2016,High School or Below,COLLECTION
342,342,25,male,30,1000,9/11/2016,10/10/2016,High School or Below,COLLECTION
343,343,39,male,15,800,9/12/2016,9/26/2016,college,COLLECTION
344,344,28,male,30,1000,9/12/2016,11/10/2016,college,COLLECTION
345,345,26,male,30,1000,9/12/2016,10/11/2016,college,COLLECTION

In [23]:
from sklearn.preprocessing import LabelEncoder
num=LabelEncoder()
data['Gender']=num.fit_transform(data['Gender'].astype(str))
data['loan_status']=num.fit_transform(data['loan_status'].astype(str))
data['education']=num.fit_transform(data['education'].astype(str))
data

,customer,age,Gender,terms,Principal,effective_date,due_date,education,loan_status
0,0,45,1,30,1000,9/8/2016,10/7/2016,1,1
1,1,33,0,30,1000,9/8/2016,10/7/2016,0,1
2,2,27,1,15,1000,9/8/2016,9/22/2016,3,1
3,3,28,0,30,1000,9/9/2016,10/8/2016,3,1
4,4,29,1,30,1000,9/9/2016,10/8/2016,3,1
...,...,...,...,...,...,...,...,...,...
341,341,32,1,15,800,9/11/2016,9/25/2016,1,0
342,342,25,1,30,1000,9/11/2016,10/10/2016,1,0
343,343,39,1,15,800,9/12/2016,9/26/2016,3,0
344,344,28,1,30,1000,9/12/2016,11/10/2016,3,0
345,345,26,1,30,1000,9/12/2016,10/11/2016,3,0

In [24]:
X=data[['age','Gender','terms','Principal','education']].values
y=data['loan_status'].values
X[0:5]
#y[0:5]

array([[  45,    1,   30, 1000,    1],
       [  33,    0,   30, 1000,    0],
       [  27,    1,   15, 1000,    3],
       [  28,    0,   30, 1000,    3],
       [  29,    1,   30, 1000,    3]], dtype=int64)

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (276, 5) (276,)
Test set: (70, 5) (70,)

In [85]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm

In [86]:
from sklearn.metrics import jaccard_score
from sklearn.metrics import log_loss
from sklearn.metrics import f1_score
from sklearn import metrics

def JS(y_test,yhat,k):
    js=jaccard_score(y_test, yhat,pos_label=k)
    return js
def F1(y_test,yhat):
    f1=f1_score(y_test, yhat, average='weighted') 
    return f1
def LoL(y_test,yhat_prob):
    lol=log_loss(y_test, yhat_prob)
    return lol

In [87]:
# K NEIGHBORS CLASSIFIER

Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))

for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])
    
k = mean_acc.argmax()+1 #k for max accuracy
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)

yhat_knc=neigh.predict(X_test)
yhat_prob_knc=neigh.predict_proba(X_test)

In [88]:
# ACCURACY FOR K NEIGHBORS CLASSIFIER

print('Jcard Score of K NEIGHBORS classifier is',JS(y_test,yhat_knc,1))
print('F1 of K NEIGHBORS classifier is',F1(y_test,yhat_knc))
print('Logloss of K NEIGHBORS classifier is',LoL(y_test,yhat_prob_knc))

Jcard Score of K NEIGHBORS classifier is 0.6764705882352942
F1 of K NEIGHBORS classifier is 0.5924040871409292
Logloss of K NEIGHBORS classifier is 3.481976156054948

In [89]:
# DECISION TREE CLASSIFIER
LoanTree = DecisionTreeClassifier(criterion="gini", max_depth = 4)
LoanTree.fit(X_train,y_train)
preTree = LoanTree.predict(X_test)
preTree_prob = LoanTree.predict_proba(X_test)

In [90]:
# ACCURACY OF DECISION TREE

print('Jcard Score of DECISION TREE classifier is',JS(y_test,preTree,1))
print('F1 of DECISION TREE classifier is',F1(y_test,preTree))
print('Logloss of DECISION TREE is',LoL(y_test,preTree_prob))

Jcard Score of DECISION TREE classifier is 0.6714285714285714
F1 of DECISION TREE classifier is 0.5394383394383394
Logloss of DECISION TREE is 0.6408570221998444

In [91]:
# LOGISTIC REGRESSION

LR=LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
yhat_lr=LR.predict(X_test)
yhat_prob_lr=LR.predict_proba(X_test)

In [92]:
# ACCURACY OF LOGISTIC REGRESSION

print('Jcard Score of LOGISTIC REGRESSION classifier is',JS(y_test,yhat_lr,1))
print('F1 of LOGISTIC REGRESSION classifier is',F1(y_test,yhat_lr))
print('Logloss of LOGISTIC REGRESSION is',LoL(y_test,yhat_prob_lr))

Jcard Score of LOGISTIC REGRESSION classifier is 0.6714285714285714
F1 of LOGISTIC REGRESSION classifier is 0.5394383394383394
Logloss of LOGISTIC REGRESSION is 0.6555179547755998

In [93]:
# SUPPORT VECTOR MACHINE

sv = svm.SVC(kernel='rbf')
sv.fit(X_train,y_train)

yhat_svm=sv.predict(X_test)
yhat_prob_svm=sv.predict(X_test)

In [94]:
# ACCURACY OF SVM

print('Jcard Score of SUPPORT VECTOR MACHINE classifier is',JS(y_test,yhat_svm,1))
print('F1 of SUPPORT VECTOR MACHINE classifier is',F1(y_test,yhat_svm))
print('Logloss of STANDARD VECTOR MACHINE is',LoL(y_test,yhat_prob_svm))

Jcard Score of SUPPORT VECTOR MACHINE classifier is 0.6714285714285714
F1 of SUPPORT VECTOR MACHINE classifier is 0.5394383394383394
Logloss of STANDARD VECTOR MACHINE is 11.348717826054862